import { Card } from "@mui/material";
import React from "react";
import Styles from "./privacy.module.css";
import Link from "next/link";

const PrivacyPolicy = () => {
  const ExamplesofCookies = [
    {
      content:
        "Session Cookies: We use Session Cookies to operate our Service.",
    },
    {
      content:
        "Preference Cookies: We use Preference Cookies to remember your preferences and various settings",
    },
    {
      content:
        "Security Cookies: We use Security Cookies for security purposes.",
    },
  ];
  const UseofData = [
    {
      content: "To provide and maintain our Service",
    },
    {
      content: "To notify you about changes to our Service",
    },
    {
      content:
        "To allow you to participate in interactive features of our Service when you choose to do so",
    },
    {
      content: "To provide customer support",
    },
    {
      content:
        "To gather analysis or valuable information so that we can improve our Service",
    },
    {
      content: "monitor the usage of our Service",
    },
    {
      content: "To detect, prevent and address technical issues",
    },
    {
      content:
        "To provide you with news, special offers and general information about other goods, services, and events which we offer that are like those that you have already purchased or enquired about unless you have opted not to receive such information",
    },
  ];
  return (
    <>
      <div className="h-auto bg-cover bg-center relative">
        <div
          className="absolute inset-0 bg-black "
          style={{
            backgroundImage: `url(${"/privacy/privacy-policy.jpg"})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        />
        <div className="flex h-[350px] items-center justify-center ">
          <h1 className="mb-4 text-3xl text-white z-10">Privacy Policy</h1>
        </div>
      </div>
      <div className="bg-[#f3f3f3]">
        <div className={`container mx-auto ${Styles.paddingcontainer} `}>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <p>
                This page informs you of our policies regarding the collection,
                use and disclosure of personal data when you use our Service and
                the choices you have associated with that data.
              </p>
              <p>
                We use your data to provide and improve the Service. By using
                the Service, you agree to the collection and use of information
                in accordance with this policy. Unless otherwise defined in this
                Privacy Policy, the terms used in this Privacy Policy have the
                same meanings as in our Terms and Conditions, accessible from{" "}
                {/* <Link
                  href={`https://www.2phtravel.com/`}
                  className="hover:text-customRed cursor-pointer"
                > */}
                https://www.2phtravel.com
                {/* </Link> */}
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h1 className=" text-customBlue">Definitions</h1>
              <br></br>
              <div className="mr-3">
                <h2>Service</h2>
                <p>
                  Service is the{" "}
                  {/* <Link
                    href={`https://www.2phtravel.com/`}
                    className="hover:text-customRed cursor-pointer"
                  > */}
                  https://www.2phtravel.com
                  {/* </Link>{" "} */}
                  website operated by DBA 2PH Travel
                </p>
                <br></br>
                <h2>Personal Data</h2>
                <p>
                  Personal Data means data about a living individual who can be
                  identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                </p>
                <br></br>
                <h2>Usage Data</h2>
                <p>
                  Usage Data is data collected automatically either generated by
                  the use of the Service or from the Service infrastructure
                  itself (for example, the duration of a page visit).
                </p>
                <br></br>
                <h2>Cookies</h2>
                <p>
                  Cookies are small files stored on your device (computer or
                  mobile device).
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div className="mr-3">
                <h4>
                  <b className=" text-customBlue">
                    Information Collection and Use
                  </b>
                </h4>
                <p className="mt-3">
                  {`We collect several different types of information for various purposes to provide and improve our Service to you.`}
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">
                  Types of Data Collected
                </b>
              </h4>
              <p className="mt-3">
                <b>Personal Data</b>
                {` While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:`}
              </p>
              <div className="mt-3">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
              </div>
              <p className="mt-3">
                We may use your Personal Data to contact you with newsletters,
                marketing or promotional materials and other information that
                may be of interest to you. You may opt out of receiving any, or
                all, of these communications from us by following the
                unsubscribe link or the instructions provided in any email we
                send.
              </p>

              <p className="mt-3">
                <b>Usage Data:</b>
                <br />
                {`We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.`}
              </p>
              <p className="mt-3">
                <b>Location Data:</b>
                <br />
                {`We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.
You can enable or disable location services when you use our Service at any time by way of your device settings.
`}
              </p>
              <p className="mt-3">
                <b>Tracking Cookies Data:</b>
                <br />
                {` We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.`}
              </p>
              <p className="mt-3">
                {` Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.`}
              </p>
              <p className="mt-3">
                {` You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.`}
              </p>
              <br></br>
              <h4>
                <b className="text-customBlue text-[20px]">
                  Examples of Cookies we use:
                </b>
              </h4>

              {ExamplesofCookies.map((item, index) => (
                <div key={index}>
                  <li>{item.content}</li>
                </div>
              ))}
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">Use of Data</b>
              </h4>
              <p className="mb-2">
                2PH Travel uses the collected data for various purposes:
              </p>
              {UseofData.map((item, index) => (
                <div key={index}>
                  <li>{item.content}</li>
                </div>
              ))}
            </Card>
          </div>

          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Transfer of Data
                </b>
              </h4>
              <p className="mb-2">
                Your information, including Personal Data, may be transferred to
                — and maintained on — computers located outside of your state,
                province, country, or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction.
                <br />
                If you are located outside the United States and choose to
                provide information to us, please note that we transfer the
                data, including Personal Data, to the United States and process
                it there. <br />
                Your consent to this Privacy Policy followed by your submission
                of such information represents your agreement to that transfer.{" "}
                <br /> 2PH Travel will take all the steps reasonably necessary
                to ensure that your data is treated securely and in accordance
                with this Privacy Policy and no transfer of your Personal Data
                will take place to an organization or a country unless there are
                adequate controls in place including the security of your data
                and other personal information.
              </p>
              <br></br>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Disclosure of Data
                </b>
              </h4>
              <h2>Disclosure for Law Enforcement</h2>
              <p>
                Under certain circumstances, 2PH Travel may be required to
                disclose your Personal Data if required to do so by law or in
                response to valid requests by public authorities (e.g. a court
                or a government agency).
              </p>
              <br></br>
              <h2>Legal Requirements</h2>
              <p>
                2PH Travel may disclose your Personal Data in the good faith
                belief that such action is necessary to:
              </p>
              <ul
                style={{ listStyle: "disc", marginLeft: "15px" }}
                className="mt-2"
              >
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To comply with a legal obligation
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To protect and defend the rights or property of 2PH Travel
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To prevent or investigate possible wrongdoing in connection
                  with the Service
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To protect the personal safety of users of the Service or the
                  public
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To protect against legal liability
                </li>
              </ul>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Security of Data
                </b>
              </h4>

              <p>
                The security of your data is important to us but remember that
                no method of transmission over the Internet or method of
                electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your Personal Data, we
                cannot guarantee its absolute security.
              </p>

              <p>
                Our Policy on Do Not Track Signals under the California Online
                Protection Act (CalOPPA) We do not support Do Not Track (DNT).
                Do Not Track is a preference you can set in your web browser to
                inform websites that you do not want to be tracked. You can
                enable or disable Do Not Track by visiting the Preferences or
                Settings page of your web browser.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Our Policy on Do Not Track Signals under the California Online
                  Protection Act (CalOPPA)
                </b>
              </h4>

              <p>
                We do not support Do Not Track (DNT). Do Not Track is a
                preference you can set in your web browser to inform websites
                that you do not want to be tracked.
              </p>

              <p>
                You can enable or disable Do Not Track by visiting the
                Preferences or Settings page of your web browser.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Service Providers
                </b>
              </h4>

              <p>
                We may employ third party companies and individuals to
                facilitate our Service Service Providers, provide the Service on
                our behalf, perform Service-related services, or assist us in
                analyzing how our Service is used.
              </p>

              <p>
                These third parties have access to your Personal Data only to
                perform these tasks on our behalf and are obligated not to
                disclose or use it for any other purpose.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Behavioral Remarketing
                </b>
              </h4>
              <p>
                2PH Travel uses remarketing services to advertise on third party
                websites to you after you visited our Service. We and our
                third-party vendors use cookies to inform, optimize and serve
                ads based on your past visits to our Service.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {`Google Ads (AdWords)`}
                </b>
              </h4>
              <p className="mb-2">
                Google Ads (AdWords) remarketing service is provided by Google
                Inc. You can opt-out of Google Analytics for Display Advertising
                and customize the Google Display Network ads by visiting the
                Google Ads Settings page:{" "}
                <a href="http://www.google.com/settings/ads">
                  http://www.google.com/settings/ads
                </a>
                <br />
                Google also recommends installing the Google Analytics Opt-out
                Browser Add-on -{" "}
                <a href="https://tools.google.com/dlpage/gaoptout">
                  https://tools.google.com/dlpage/gaoptout
                </a>{" "}
                - for your web browser. <br />
                Google Analytics Opt-out Browser Add-on provides visitors with
                the ability to prevent their data from being collected and used
                by Google Analytics.
                <br /> For more information on the privacy practices of Google,
                please visit the Google Privacy Terms web page:{" "}
                <a href="https://policies.google.com/privacy?hl=en">
                  https://policies.google.com/privacy?hl=en
                </a>
              </p>

              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {`Facebook`}
                </b>
              </h4>
              <p className="mb-2">
                Facebook remarketing service is provided by Facebook Inc. You
                can learn more about interest-based advertising from Facebook by
                visiting this page:{" "}
                <a
                  href="https://www.facebook.com/help/164968693837950"
                  className="text-customBlue"
                  target="blank"
                >
                  https://www.facebook.com/help/164968693837950
                </a>
                <br />
                To opt-out from Facebooks interest-based ads, follow these
                instructions from Facebook:{" "}
                <a
                  href="https://www.facebook.com/help/568137493302217"
                  className="text-customBlue"
                  target="blank"
                >
                  https://www.facebook.com/help/568137493302217
                </a>
                <br />
                Facebook adheres to the Self-Regulatory Principles for Online
                Behavioral Advertising established by the Digital Advertising
                Alliance. You can also opt-out from Facebook and other
                participating companies through the Digital Advertising Alliance
                in the USA{" "}
                <a
                  href="http://www.aboutads.info/choices/"
                  className="text-customBlue"
                  target="blank"
                >
                  http://www.aboutads.info/choices/
                </a>{" "}
                <br /> the Digital Advertising Alliance of Canada in Canada{" "}
                <a
                  href="http://youradchoices.ca/"
                  target="blank"
                  className="text-customBlue"
                >
                  http://youradchoices.ca/
                </a>{" "}
                <br />
                or the European Interactive Digital Advertising Alliance in
                Europe{" "}
                <a
                  href="http://www.youronlinechoices.eu/"
                  className="text-customBlue"
                  target="blank"
                >
                  http://www.youronlinechoices.eu/
                </a>
                <br /> or opt-out using your mobile device settings. For more
                information on the privacy practices of Facebook, please visit
                Facebooks Data Policy:{" "}
                <a
                  href="https://www.facebook.com/privacy/explanation"
                  className="text-customBlue"
                  target="blank"
                >
                  https://www.facebook.com/privacy/explanation
                </a>
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {` Links to Other Sites`}
                </b>
              </h4>

              <p>
                Our Service may contain links to other sites that are not
                operated by us. If you click a third party link, you will be
                directed to that third party&rsquo;s site. We strongly advise
                you to review the Privacy Policy of every site you visit.
              </p>
              <p>
                We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third party sites
                or services.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {` Childrens Privacy`}
                </b>
              </h4>

              <p>
                Our Service does not address anyone under the age of 18
                (Children). We do not knowingly collect personally identifiable
                information from anyone under the age of 18. If you are a parent
                or guardian and you are aware that your Child has provided us
                with Personal Data, please contact us. If we become aware that
                we have collected Personal Data from children without
                verification of parental consent, we take steps to remove that
                information from our servers.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {`  Changes to This Privacy Policy`}
                </b>
              </h4>

              <p>
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page. We will let you know via email and/or a prominent
                notice on our Service, prior to the change becoming effective
                and update the effective date at the top of this Privacy Policy.
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h1>Contact Us</h1>
              <h1>
                If you have any questions about this Privacy Policy, please
                contact us:
              </h1>

              <li className=" ">By email: support@2phtravel.com</li>
              <li className=" ">
                By visiting this page on our website: https://www.2phtravel.com
              </li>
              <li>By phone number: +1 855-767-7778</li>
            </Card>
          </div>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
