import { Card } from "@mui/material";
import React from "react";
import Styles from "./privacy.module.css";
import Link from "next/link";

const PrivacyPolicy = () => {
  const ExamplesofCookies = [
    {
      content:
        "Session Cookies: We use Session Cookies to operate our Service.",
    },
    {
      content:
        "Preference Cookies: We use Preference Cookies to remember your preferences and various settings",
    },
    {
      content:
        "Security Cookies: We use Security Cookies for security purposes.",
    },
  ];
  const UseofData = [
    {
      content: "To provide and maintain our Service",
    },
    {
      content: "To notify you about changes to our Service",
    },
    {
      content:
        "To allow you to participate in interactive features of our Service when you choose to do so",
    },
    {
      content: "To provide customer support",
    },
    {
      content:
        "To gather analysis or valuable information so that we can improve our Service",
    },
    {
      content: "monitor the usage of our Service",
    },
    {
      content: "To detect, prevent and address technical issues",
    },
    {
      content:
        "To provide you with news, special offers and general information about other goods, services, and events which we offer that are like those that you have already purchased or enquired about unless you have opted not to receive such information",
    },
  ];
  return (
    <>
      <div className="h-auto bg-cover bg-center relative">
        <div
          className="absolute inset-0 bg-black "
          style={{
            backgroundImage: `url(${"/privacy/privacy-policy.jpg"})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        />
        <div className="flex h-[350px] items-center justify-center ">
          <h1 className="mb-4 text-3xl text-white z-10">Privacy Policy</h1>
        </div>
      </div>
      <div className="bg-[#f3f3f3]">
        <div className={`container mx-auto ${Styles.paddingcontainer} `}>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <p>
                This page informs you of our policies regarding the collection,
                use and disclosure of personal data when you use our Service and
                the choices you have associated with that data.
              </p>
              <p>
                We use your data to provide and improve the Service. By using
                the Service, you agree to the collection and use of information
                in accordance with this policy. Unless otherwise defined in this
                Privacy Policy, the terms used in this Privacy Policy have the
                same meanings as in our Terms and Conditions, accessible from{" "}
                {/* <Link
                  href={`https://www.2phtravel.com/`}
                  className="hover:text-customRed cursor-pointer"
                > */}
                https://www.2phtravel.com
                {/* </Link> */}
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h1 className=" text-customBlue">Definitions</h1>
              <br></br>
              <div className="mr-3">
                <h2>Service</h2>
                <p>
                  Service is the{" "}
                  {/* <Link
                    href={`https://www.2phtravel.com/`}
                    className="hover:text-customRed cursor-pointer"
                  > */}
                  https://www.2phtravel.com
                  {/* </Link>{" "} */}
                  website operated by DBA 2PH Travel
                </p>
                <br></br>
                <h2>Personal Data</h2>
                <p>
                  Personal Data means data about a living individual who can be
                  identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                </p>
                <br></br>
                <h2>Usage Data</h2>
                <p>
                  Usage Data is data collected automatically either generated by
                  the use of the Service or from the Service infrastructure
                  itself (for example, the duration of a page visit).
                </p>
                <br></br>
                <h2>Cookies</h2>
                <p>
                  Cookies are small files stored on your device (computer or
                  mobile device).
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div className="mr-3">
                <h4>
                  <b className=" text-customBlue">
                    Information Collection and Use
                  </b>
                </h4>
                <p className="mt-3">
                  {`We collect several different types of information for various purposes to provide and improve our Service to you.`}
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">
                  Types of Data Collected
                </b>
              </h4>
              <p className="mt-3">
                <b>Personal Data</b>
                {` While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:`}
              </p>
              <div className="mt-3">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
              </div>
              <p className="mt-3">
                We may use your Personal Data to contact you with newsletters,
                marketing or promotional materials and other information that
                may be of interest to you. You may opt out of receiving any, or
                all, of these communications from us by following the
                unsubscribe link or the instructions provided in any email we
                send.
              </p>

              <p className="mt-3">
                <b>Usage Data:</b>
                <br />
                {`We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.`}
              </p>
              <p className="mt-3">
                <b>Location Data:</b>
                <br />
                {`We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.
You can enable or disable location services when you use our Service at any time by way of your device settings.
`}
              </p>
              <p className="mt-3">
                <b>Tracking Cookies Data:</b>
                <br />
                {` We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.`}
              </p>
              <p className="mt-3">
                {` Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.`}
              </p>
              <p className="mt-3">
                {` You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.`}
              </p>
              <br></br>
              <h4>
                <b className="text-customBlue text-[20px]">
                  Examples of Cookies we use:
                </b>
              </h4>

              {ExamplesofCookies.map((item, index) => (
                <div key={index}>
                  <li>{item.content}</li>
                </div>
              ))}
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">Use of Data</b>
              </h4>
              <p className="mb-2">
                2PH Travel uses the collected data for various purposes:
              </p>
              {UseofData.map((item, index) => (
                <div key={index}>
                  <li>{item.content}</li>
                </div>
              ))}
            </Card>
          </div>

          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Transfer of Data
                </b>
              </h4>
              <p className="mb-2">
                Your information, including Personal Data, may be transferred to
                — and maintained on — computers located outside of your state,
                province, country, or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction.
                <br />
                If you are located outside the United States and choose to
                provide information to us, please note that we transfer the
                data, including Personal Data, to the United States and process
                it there. <br />
                Your consent to this Privacy Policy followed by your submission
                of such information represents your agreement to that transfer.{" "}
                <br /> 2PH Travel will take all the steps reasonably necessary
                to ensure that your data is treated securely and in accordance
                with this Privacy Policy and no transfer of your Personal Data
                will take place to an organization or a country unless there are
                adequate controls in place including the security of your data
                and other personal information.
              </p>
              <br></br>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Disclosure of Data
                </b>
              </h4>
              <h2>Disclosure for Law Enforcement</h2>
              <p>
                Under certain circumstances, 2PH Travel may be required to
                disclose your Personal Data if required to do so by law or in
                response to valid requests by public authorities (e.g. a court
                or a government agency).
              </p>
              <br></br>
              <h2>Legal Requirements</h2>
              <p>
                2PH Travel may disclose your Personal Data in the good faith
                belief that such action is necessary to:
              </p>
              <ul
                style={{ listStyle: "disc", marginLeft: "15px" }}
                className="mt-2"
              >
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To comply with a legal obligation
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To protect and defend the rights or property of 2PH Travel
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To prevent or investigate possible wrongdoing in connection
                  with the Service
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To protect the personal safety of users of the Service or the
                  public
                </li>
                <li
                  style={{ listStyle: "disc", marginLeft: "18px" }}
                  className="mt-2"
                >
                  To protect against legal liability
                </li>
              </ul>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Security of Data
                </b>
              </h4>

              <p>
                The security of your data is important to us but remember that
                no method of transmission over the Internet or method of
                electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your Personal Data, we
                cannot guarantee its absolute security.
              </p>

              <p>
                Our Policy on Do Not Track Signals under the California Online
                Protection Act (CalOPPA) We do not support Do Not Track (DNT).
                Do Not Track is a preference you can set in your web browser to
                inform websites that you do not want to be tracked. You can
                enable or disable Do Not Track by visiting the Preferences or
                Settings page of your web browser.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Our Policy on Do Not Track Signals under the California Online
                  Protection Act (CalOPPA)
                </b>
              </h4>

              <p>
                We do not support Do Not Track (DNT). Do Not Track is a
                preference you can set in your web browser to inform websites
                that you do not want to be tracked.
              </p>

              <p>
                You can enable or disable Do Not Track by visiting the
                Preferences or Settings page of your web browser.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Service Providers
                </b>
              </h4>

              <p>
                We may employ third party companies and individuals to
                facilitate our Service Service Providers, provide the Service on
                our behalf, perform Service-related services, or assist us in
                analyzing how our Service is used.
              </p>

              <p>
                These third parties have access to your Personal Data only to
                perform these tasks on our behalf and are obligated not to
                disclose or use it for any other purpose.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  Behavioral Remarketing
                </b>
              </h4>
              <p>
                2PH Travel uses remarketing services to advertise on third party
                websites to you after you visited our Service. We and our
                third-party vendors use cookies to inform, optimize and serve
                ads based on your past visits to our Service.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {`Google Ads (AdWords)`}
                </b>
              </h4>
              <p className="mb-2">
                Google Ads (AdWords) remarketing service is provided by Google
                Inc. You can opt-out of Google Analytics for Display Advertising
                and customize the Google Display Network ads by visiting the
                Google Ads Settings page:{" "}
                <a href="http://www.google.com/settings/ads">
                  http://www.google.com/settings/ads
                </a>
                <br />
                Google also recommends installing the Google Analytics Opt-out
                Browser Add-on -{" "}
                <a href="https://tools.google.com/dlpage/gaoptout">
                  https://tools.google.com/dlpage/gaoptout
                </a>{" "}
                - for your web browser. <br />
                Google Analytics Opt-out Browser Add-on provides visitors with
                the ability to prevent their data from being collected and used
                by Google Analytics.
                <br /> For more information on the privacy practices of Google,
                please visit the Google Privacy Terms web page:{" "}
                <a href="https://policies.google.com/privacy?hl=en">
                  https://policies.google.com/privacy?hl=en
                </a>
              </p>

              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {`Facebook`}
                </b>
              </h4>
              <p className="mb-2">
                Facebook remarketing service is provided by Facebook Inc. You
                can learn more about interest-based advertising from Facebook by
                visiting this page:{" "}
                <a
                  href="https://www.facebook.com/help/164968693837950"
                  className="text-customBlue"
                  target="blank"
                >
                  https://www.facebook.com/help/164968693837950
                </a>
                <br />
                To opt-out from Facebooks interest-based ads, follow these
                instructions from Facebook:{" "}
                <a
                  href="https://www.facebook.com/help/568137493302217"
                  className="text-customBlue"
                  target="blank"
                >
                  https://www.facebook.com/help/568137493302217
                </a>
                <br />
                Facebook adheres to the Self-Regulatory Principles for Online
                Behavioral Advertising established by the Digital Advertising
                Alliance. You can also opt-out from Facebook and other
                participating companies through the Digital Advertising Alliance
                in the USA{" "}
                <a
                  href="http://www.aboutads.info/choices/"
                  className="text-customBlue"
                  target="blank"
                >
                  http://www.aboutads.info/choices/
                </a>{" "}
                <br /> the Digital Advertising Alliance of Canada in Canada{" "}
                <a
                  href="http://youradchoices.ca/"
                  target="blank"
                  className="text-customBlue"
                >
                  http://youradchoices.ca/
                </a>{" "}
                <br />
                or the European Interactive Digital Advertising Alliance in
                Europe{" "}
                <a
                  href="http://www.youronlinechoices.eu/"
                  className="text-customBlue"
                  target="blank"
                >
                  http://www.youronlinechoices.eu/
                </a>
                <br /> or opt-out using your mobile device settings. For more
                information on the privacy practices of Facebook, please visit
                Facebooks Data Policy:{" "}
                <a
                  href="https://www.facebook.com/privacy/explanation"
                  className="text-customBlue"
                  target="blank"
                >
                  https://www.facebook.com/privacy/explanation
                </a>
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {` Links to Other Sites`}
                </b>
              </h4>

              <p>
                Our Service may contain links to other sites that are not
                operated by us. If you click a third party link, you will be
                directed to that third party&rsquo;s site. We strongly advise
                you to review the Privacy Policy of every site you visit.
              </p>
              <p>
                We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third party sites
                or services.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {` Childrens Privacy`}
                </b>
              </h4>

              <p>
                Our Service does not address anyone under the age of 18
                (Children). We do not knowingly collect personally identifiable
                information from anyone under the age of 18. If you are a parent
                or guardian and you are aware that your Child has provided us
                with Personal Data, please contact us. If we become aware that
                we have collected Personal Data from children without
                verification of parental consent, we take steps to remove that
                information from our servers.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue  mb-2 text-[20px]">
                  {`  Changes to This Privacy Policy`}
                </b>
              </h4>

              <p>
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page. We will let you know via email and/or a prominent
                notice on our Service, prior to the change becoming effective
                and update the effective date at the top of this Privacy Policy.
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h1>Contact Us</h1>
              <h1>
                If you have any questions about this Privacy Policy, please
                contact us:
              </h1>

              <li className=" ">By email: support@2phtravel.com</li>
              <li className=" ">
                By visiting this page on our website: https://www.2phtravel.com
              </li>
              <li>By phone number: +1 855-767-7778</li>
            </Card>
          </div>
          {/* <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b>DATA ACCURACY</b>
                </h4>
                <br></br>
                <p>
                  This privacy policy has been compiled to better serve those
                  who are concerned with how their ‘Personally Identifiable
                  Information’ (PI) is being used online. PI, as used in US
                  privacy law and information security, is information which can
                  be used on its own or with other information to identify,
                  contact, or locate a single person, or to identify an
                  individual in context.
                </p>
                <br></br>
                <p>
                  When you give us personal information, you are telling us that
                  the information is true, accurate, complete, and current. You
                  are also telling us, that you have the authorization to
                  provide it to us It is important that the PI we hold about you
                  is accurate and current.
                </p>
                <br></br>
                <p>
                  Please read our privacy policy carefully to get a clear
                  understanding of how we collect, use, protect, or otherwise
                  handle your Personally Identifiable Information in accordance
                  with our website.
                </p>
              </div>
              <br></br>
              <div>
                <h4>
                  <b>The Categories Of Personal Information We Collect</b>
                </h4>
                <br></br>
                <p>
                  When ordering or registering on our site, you may be asked to
                  enter your name, email address, mailing address, phone number,
                  or other details to help you with your experience.
                </p>
                <br></br>
                <p>
                  We collect information from you when you place an order,
                  subscribe to a newsletter, or enter information on our site.
                </p>
                <br></br>
                <p>
                  We may use the information that/which we collect from you when
                  you register, make a purchase, sign up for our newsletter,
                  respond to a survey or marketing communication, surf the
                  website, or use certain other site features in the following
                  ways:{" "}
                </p>

                <ul
                  style={{ listStyle: "disc", marginLeft: "15px" }}
                  className="mt-2"
                >
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`	To personalize the user's experience and to allow us to deliver the type of content and product offerings in which you are most interested.`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    To improve our website to serve you better.
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    To allow us to better service you in responding to your
                    customer service requests.
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    To administer a contest, promotion, survey, or other site
                    feature.
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    To quickly process your transactions
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    To send periodic emails regarding your order or other
                    products and services.
                  </li>
                </ul>
                <br></br>
                <p>
                  We may collect, use, store and transfer different kinds of PI
                  about you which we have grouped together as follows:
                </p>

                <ul
                  style={{ listStyle: "disc", marginLeft: "15px" }}
                  className="mt-2"
                >
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Identifiers</b>{" "}
                    {` or Identity Data such as a first/ middle/ last name, alias, postal address, unique personal identifier (cookie), date of birth, online identifier Internet Protocol address, or other similar identifiers.`}
                  </li>

                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Contact Data </b>{" "}
                    {` includes (billing address, delivery address, email address and telephone numbers).`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Commercial Information</b>{" "}
                    {` including requested price quotes, products or services purchased or other purchasing or consuming histories or tendencies, as well as Financial Data (bank account and payment card details) and Transaction Data (details about payments to and from you and other details of products and services you have purchased from us).`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Network Activity Information</b>{" "}
                    {` including, but not limited to Technical Data (your login data, browser type and version, browsing history, search history, time zone setting and location, browser plug-in types and versions, operating system and Platform, and other technology on the devices you use to access our Platforms), and information regarding your interaction with our Platforms (Usage Data).`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Geolocation data</b> {` (country, state, or city).`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Audio </b> {`(e.g. call records) and `}
                    <b>Electronic </b>
                    {`(e.g. email threads) information `}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    <b>Inferences </b>{" "}
                    {` (conclusions) drawn from any of the PI collected by ITN, including, but not limited to Profile Data (your preferences, characteristics, psychological trends, behavior, attitudes, intelligence, feedback, and survey responses) and Marketing Data (your preferences in receiving marketing from us and our partners and your communication preferences).`}
                  </li>
                </ul>
                <br></br>
                <p>
                  We also collect, use, and share Aggregated Data such as
                  statistical or demographic data for any purpose. Aggregated
                  Data could be derived from your PI, but is not considered PI
                  in law as this data will not directly or indirectly reveal
                  your identity. For example, we may aggregate your Network
                  Activity Information to calculate the percentage of users
                  accessing a specific Platform feature. However, if we combine
                  or connect Aggregated Data with your PI, so that it can
                  directly or indirectly identify you, we treat the combined
                  data as PI which will be used in accordance with this privacy
                  policy.
                </p>
                <br></br>
                <p>
                  <b> Customer support</b> If you choose to contact our customer
                  support services, we will collect any inquiries, complaints,
                  or other information that you may submit to our support team.
                  We do not collect any Special Categories of PI about you (this
                  includes details about your race or ethnicity, religious or
                  philosophical beliefs, sex life, sexual orientation, political
                  opinions, trade union membership, information about your
                  health, and genetic and biometric data). Nor do we collect any
                  information about criminal convictions and offenses.
                </p>
              </div>
              <br></br>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b className="text-customBlue text-[20px]">Children</b>
                </h4>

                <p className="mt-3">
                  ITN does not knowingly collect PI from minors, except if the
                  minor is one of travelers. If we become aware that a minor is
                  attempting to submit PI, we will remove this information from
                  our records. If you are the parent/legal guardian of a minor
                  who has given us PI, please contact us so we can delete it.
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b className="text-customBlue text-[20px]">
                    If You Fail To Provide Personal Information
                  </b>
                </h4>

                <p className="mt-3">
                  Where we collect PI required by law or under the terms of a
                  contract, and you fail to provide that PI when requested, we
                  may not be able to perform the contract we have or are trying
                  to enter with you (for example, to provide you with goods or
                  services). In this case, we may have to cancel a product or
                  service you have with us, but we will notify you if this is
                  the case at the time.
                </p>
                <br></br>
                <h4>
                  <b>Methods Used for Collecting Your Personal Information</b>
                </h4>
                <br />
                <p>
                  Currently, the methods we and our third-party service provider
                  use to collect your personal data are
                </p>

                <p className="mt-3">
                  <b>The personal information you give to us: </b> We collect
                  your personal information directly from you
                </p>

                <p>
                  For example, you provide us with your personal information
                  when you register or book travel, contact our customer
                  support.
                </p>
                <br />
                <p>
                  At the same time, we have the passive ability to collect some
                  personal information. How does this happen? When you visit our
                  website, you provide the opportunity to collect certain
                  information about yourself. In addition, when you are using
                  our website, cookies and other similar technologies can help
                  us automatically collect technical data about your equipment,
                  navigation actions, and patterns. See the cookies section of
                  this Privacy Policy for further information on the purposes
                  for which we collect and use this information.
                </p>
                <br />
                <p>
                  <b> Voice Calls:</b> We may record or monitor calls to and
                  from our Customer Support Team for contractual reasons,
                  quality control purposes, analytics, staff training and/or to
                  protect us in the event of a legal dispute. Any personal data
                  obtained from you during the call will be treated in
                  accordance with this Privacy Policy.
                </p>
                <br />
                <p>
                  <b> From Other Sources: </b> We may receive your Personal
                  Information from other sources, such as public databases,
                  joint marketing partners, social media platforms (including
                  from people with whom you are friends or otherwise connected),
                  and other third parties, to the extent permitted by applicable
                  law.
                </p>
                <br />
                <p>
                  <b> Automatic Information: </b>We automatically collect
                  certain information about your computer when you visit our
                  website. For example, we record your IP address, Web browser
                  software (such as Firefox, Safari, or Internet Explorer), and
                  referring websites. We also may gather information about your
                  online activity, such as trips or activities viewed and
                  bookings made. We collect this automatic information to
                  customize your user experience and protect against fraud. See
                  also Cookies and other technologies below.
                </p>
                <br />
                <p>
                  In order to help you find the nearest hotel, train station,
                  airport, or send some important messages to you, our system
                  can use the attributes and settings of your device that allow
                  us to determine physical location.
                </p>
                <br />
                <p>
                  You can opt-out of this communication at any time by
                  contacting us via phone or email.
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b className="text-customBlue text-[20px]">
                    For What Purpose We Use Your Personal Information
                  </b>
                </h4>

                <p className="mt-3">
                  We will use your PI for the following purposes:
                </p>
                <br></br>

                <p className="mt-3">
                  <b>Improving our services: </b> To provide you and improve our
                  Platforms and services, to better understand the users of our
                  Platforms and services, and to protect our property and to
                  prevent damage to them.
                </p>
                <p className="mt-3">
                  <b>Regular customers: </b> If you have ever requested a price
                  quote or purchased our services, we treat you as the Regular
                  (loyal) Customer. Regular Customers have plenty of benefits:
                  <ul
                    style={{ listStyle: "disc", marginLeft: "15px" }}
                    className="mt-2"
                  >
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`	become experts of using our services;`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`   receive the most relevant price quotes. `}
                    </li>
                  </ul>
                </p>
                <p className="mt-2">
                  {" "}
                  According to our policy, we may contact you as a Regular
                  Customer via email/phone saved within previous requests and
                  transactions. Such cases may be, for example, when you have
                  accidentally provided the wrong email/phone or when you cannot
                  be reached via email/ phone left in the last request/
                  purchase. If you want to opt-out, please contact us.
                </p>
                <p className="mt-3">
                  <b>Marketing activities: </b> We use your information for
                  marketing purposes. These activities may include:
                  <ul
                    style={{ listStyle: "disc", marginLeft: "15px" }}
                    className="mt-2"
                  >
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To send booking confirmations;`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To send alerts and notifications you have subscribed to, including to your mobile device;`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To solicit reviews;`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To update you regarding itineraries processed by our service;`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To communicate with you if you have contacted ITN customer support;`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To send you information servicing and administrative emails`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To send you information about services, offered by ITN or our business partners, that we believe you would be interested in;`}
                    </li>
                  </ul>
                </p>
                <p className="mt-3">
                  To communicate with you, including as follows:
                  <ul
                    style={{ listStyle: "disc", marginLeft: "15px" }}
                    className="mt-2"
                  >
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`To send you marketing emails and/or text messages from ITN address regarding our services or those of our partners, if you have opted-in to receive emails and/or text messages from us or have transacted with us, and as permitted by law. You can easily unsubscribe from these marketing communications at any time by clicking on the “Unsubscribe” link included in the newsletter or by texting STOP via sms. To display more relevant advertising and recommendations, or suppress advertising and content that you might find irrelevant. This advertising might be shown to you on our Platforms as well as third party platforms (including Google and social media sites like Facebook) and include information or offers that we, or our business partners’, believe you will find interesting. Individualized advertising may be based on information collected through cookies or other tracking technologies. You can opt out from Google and Facebook ad personalization any time.`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`If you choose to participate in promotional activities, relevant information may be used to administer these promotions. `}
                    </li>
                  </ul>
                </p>

                <p className="mt-3">
                  <b>Bookings: </b> We and our travel partners use your PI to
                  process your bookings and store your itinerary information
                  where applicable.
                </p>
                <p className="mt-3">
                  <b> Legal purposes: </b> In certain cases, we may need to use
                  your information to handle and resolve legal disputes, for
                  regulatory investigations and compliance or to enforce the
                  terms of use of the service.
                </p>
                <p className="mt-3">
                  <b>Performance of a contract: </b> The use of your PI may be
                  necessary to perform the services and provide you products
                  that you have requested from us. For example, if you make a
                  booking on our Platform, we need to collect PI from you to
                  complete the booking.
                </p>
                <p className="mt-3">
                  <b>Consent: </b> We may rely on your consent to use your PI
                  for certain direct marketing purposes. You can withdraw your
                  consent anytime by contacting us. We have set out below, in a
                  table format, a description of all the ways we plan to use
                  your PI.
                </p>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b className="text-customBlue text-[20px]">
                    Change Of Purpose
                  </b>
                </h4>

                <p className="mt-3">
                  We will only use your PI for the purposes for which we
                  collected it, unless we reasonably consider that we need to
                  use it for another reason and that reason is compatible with
                  the original purpose. If you wish to get an explanation as to
                  how the processing for the new purpose is compatible with the
                  original purpose, please contact us.
                </p>

                <h4 className="mt-3">
                  <b>About Electronic Communications</b>
                </h4>

                <p className="mt-3">
                  Consistent with the above purposes and as permitted by
                  applicable law, we may communicate with you via electronic
                  messages, including email, text message, or mobile push
                  notification to:
                  <ul
                    style={{ listStyle: "disc", marginLeft: "15px" }}
                    className="mt-2"
                  >
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`Send you information relating to our products and Services. This may include booking confirmations and updates, technical notices, updates, security alerts, support, and administrative messages.`}
                    </li>
                    <li
                      style={{ listStyle: "disc", marginLeft: "18px" }}
                      className="mt-2"
                    >
                      {`Send you marketing communications. In other situations, we may communicate with you about contests, offers, promotions, rewards, upcoming events, and other news about products and Services offered by us, our group companies, our travel partners, and other business partners.`}
                    </li>
                  </ul>
                </p>

                <p className="mt-3">
                  <b>Email Communications: </b> . From time to time, we may send
                  you emails containing information about your apparent
                  travel-related or activity interests. We do this to make it
                  easy for you to take advantage of travel-related or other
                  opportunities on our website
                </p>
                <br />
                <p>
                  If you no longer want to receive marketing and promotional
                  emails from us, you may click on the “unsubscribe” link in
                  such emails to opt out of future marketing email
                  communications. If you have an account, you may also opt out
                  of marketing emails in your account settings. Please note that
                  even if you opt out of receiving marketing communications from
                  one or all our Services, we will still send you
                  service-related communications, such as confirmations of any
                  future bookings you make.
                </p>
                <p className="mt-3">
                  <b>Push Notifications (on Mobile Devices) </b> . You can use
                  the settings on your mobile device to enable or turn off
                  mobile push notifications from us.
                </p>
                <p className="mt-3">
                  <b>SMS Message Service: </b> .With your consent, where
                  required, we may contact you at the mobile phone number that
                  you provide to us by way of direct dial calls, autodialed and
                  prerecorded message calls, and text messages in connection
                  with the above purposes.
                </p>
                <p className="mt-3">
                  By signing in to the SMS message service, you consent to
                  receive recurring autodialed marketing texts from or on behalf
                  of our Company at the mobile number you have provided to
                  opt-in. You understand that consent is not a condition of
                  purchase. Message & data rates may apply.
                </p>
                <p className="mt-3">
                  After you opt-in to receive messages online, in-person, or
                  SMS, you can cancel the SMS service at any time by just
                  replying “STOP” to the SMS message. After this, you will no
                  longer receive SMS messages from us. Unsubscribing from our
                  SMS service will not preclude us from sending you
                  service-related SMS in connection with an existing booking,
                  including us contacting you with an automated pre-recorded
                  call containing critically important travel information (e.g.,
                  Major Schedule Change Notifications via call and/or SMS
                  message). If you want to join again, just sign up as you did
                  the first time, and we will start sending SMS messages to you
                  again.
                </p>
                <p className="mt-3">
                  As always, message and data rates may apply for any messages
                  sent to you from us and to us from you. Message frequency
                  depends on the user’s interaction. If you have any questions
                  about your text plan or data plan, it is best to contact your
                  wireless provider.
                </p>
                <p className="mt-3">
                  You represent that you are the account holder for the mobile
                  telephone number(s) that you provide. You are responsible for
                  notifying us immediately if you change your mobile telephone
                  number. You may notify us of a number change by contacting us
                  via email or phone.
                </p>
                <p className="mt-3">
                  You agree to indemnify us in full for all claims, expenses,
                  and damages related to or caused in whole or in part by your
                  failure to notify us if you change your telephone number,
                  including, but not limited to, all claims, expenses, and
                  damages related to or arising under the Telephone Consumer
                  Protection Act.
                </p>
              </div>
            </Card>
          </div>

          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b className="text-customBlue text-[20px]">
                    Cases of Transmitting Information to Third Parties
                  </b>
                </h4>
                <p className="mt-3">
                  In case of need to transmit your data to third parties, we
                  will consider the following:
                </p>
                <ul
                  style={{ listStyle: "disc", marginLeft: "15px" }}
                  className="mt-2"
                >
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`only with your consent;`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`if this operation is strictly necessary to provide our services;`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`In case it is necessary to send to a lawyer the information, to start the procedure for resolving the litigation;`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`In case it is necessary to protect the integrity and transparency of our company;`}
                  </li>
                </ul>
                <p className="mt-3">
                  Also, there is a possibility to share information about your
                  personal data with our business partners. Some of these
                  business partners may use your personal information for fraud
                  detection found, for an email address, to detect, prevent, or
                  otherwise address fraud, security, or technical issues. We may
                  also share your information by asking our partner to create an
                  application, questionnaire etc., for the purpose to know the
                  degree of your satisfaction with our services. Some of these
                  business partners may use your personal information for online
                  behavioral advertising purposes, or to offer you services or
                  products that we believe you may be interested in. We may also
                  share your information as otherwise described to you at the
                  time of collection. We may also share anonymous aggregated
                  usage information with partners.
                </p>
              </div>
            </Card>
          </div>

          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <div>
                <h4>
                  <b className="text-customBlue text-[20px]">CAN SPAM Act</b>
                </h4>
                <p className="mt-3">
                  The CAN SPAM act is a law that sets the rules for commercial
                  email, establishes requirements for commercial messages, gives
                  recipients the right to have email stopped from being sent to
                  them, and spells out the tough penalties for violations.
                </p>
                <p className="mt-3">We collect your email address to:</p>
                <ul
                  style={{ listStyle: "disc", marginLeft: "15px" }}
                  className="mt-2"
                >
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Send information, respond to inquiries, and or other requests or questions.`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Process orders and to send information and updates pertaining to orders`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Send additional products and/or services based on your preferences`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Market to our mailing list or continue to send emails to our clients after their original transaction has occurred`}
                  </li>
                </ul>
                <p className="mt-3">
                  In accordance with CAN SPAM, we agree to the following:
                </p>
                <ul
                  style={{ listStyle: "disc", marginLeft: "15px" }}
                  className="mt-2"
                >
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Not use false or misleading subjects or email addresses`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Identify the message as an advertisement in some reasonable way`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Include the physical address of our business or side headquarters`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Monitor third-party email marketing services for compliance, if one is used`}
                  </li>
                  <li
                    style={{ listStyle: "disc", marginLeft: "18px" }}
                    className="mt-2"
                  >
                    {`Honor opt-out/unsubscribe requests quickly allow users to unsubscribe but using the link at the bottom of each email`}
                  </li>
                </ul>
              </div>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">Your Choices</b>
              </h4>
              <br />
              <p>
                As a customer-oriented business we respect and value your
                expectations. As a result, you can make announcements and
                queries at any time regarding your concerns in privacy matters.
                Each of our marketing emails has an opt-out button and you can
                change preferences or unsubscribe at all from such communication
                at any time. Each ITN website is targeted to the current
                audience and region, therefore subscribe/unsubscribe options are
                also different. You cannot unsubscribe from servicing emails and
                administrative messages.
              </p>
            </Card>
          </div>
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">
                  How We Share Your Personal Information
                </b>
              </h4>
              <p className="mt-2 ">
                <b>Corporate affiliates and change of control</b> We may share
                your PI with our corporate affiliates and if ITN itself (or part
                of its business) is sold or otherwise changes control, owners
                would have access to your PI for the uses set out herein.
              </p>
              <p className="mt-2 ">
                <b>Service providers </b> providers We may share your PI with
                suppliers who perform services on our behalf and have agreed in
                writing to protect and not further disclose your information
              </p>
              <p className="mt-2 ">
                <b>Payment service providers and travel vendors </b> If you book
                through the Platforms, we may share your PI with the payment
                service providers, acquirer banks and the travel vendors you
                have booked with. This can include online travel agencies,
                hotels, airlines, car rental companies, and travel insurance
                providers. These third parties will process your PI as data
                controllers in accordance with their own privacy policies. If
                you contact our customer support, they may need to share
                information about your request with the relevant travel vendor
                to assist you.
              </p>
              <p className="mt-2 ">
                We enter confidentiality and PI processing terms with partners
                to ensure they comply with high levels of confidentiality and
                best practice in privacy and security standards and we regularly
                review these standards and practices.
              </p>
              <p className="mt-2 ">
                <b>Trips shared by you </b> If you use or have itineraries as
                part of our Service, you can send or grant access to your
                itinerary to anyone you choose. Your itinerary may contain
                enough details (for example, booking reference codes) to allow
                the recipient to cancel or modify your booking, perform a
                check-in, etc. You should only share your itinerary with people
                you trust. If you choose to display your itinerary on
                publicly-viewable web pages (Facebook, for instance), that
                information may be collected and used by others.
              </p>{" "}
              <p className="mt-2 ">
                <b>Information shared in public </b> If you provide us a review
                of your trip, you authorize us to publish it on all our
                Platforms under the screen name you provided. You also authorize
                us to aggregate it with other reviews.
              </p>
              <p className="mt-2 ">
                <b>Authorities </b> We may disclose PI if required by law, for
                example to law enforcement or other authorities. This includes
                court orders, subpoenas and orders arising from legal processes,
                and administrative or criminal investigations. We may also
                disclose your PI if the disclosure is necessary for the
                prevention, detection, or prosecution of criminal acts or to
                prevent other damage, or in response to a legal action or to
                enforce our rights and claims.
              </p>
              <p className="mt-2 ">
                We may also share anonymous aggregated usage information with
                others.
              </p>
            </Card>
          </div>

          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">
                  How We Store And Protect Your Data
                </b>
              </h4>
              <br />
              <p>
                Our servers and data centers are in many countries and by giving
                us your personal information, you agree that it can be shared
                with other countries that may have different and/or less strict
                confidentiality rules. As a result, your personal information
                may be subject to requests for access from Governments, Courts,
                or Law Enforcement Agencies from these countries in accordance
                with the laws of these countries. According to the legislation
                in force in such countries, we will provide the necessary
                security measures to ensure the protection of your personal
                information.
              </p>
              <br />
              <p>
                We have adopted the appropriate security measures to avoid
                accidental loss, use or access to your personal data in an
                unauthorized manner, alteration, or disclosure. In addition, we
                restrict access to your personal data only to those employees,
                agents, contractors, and other third parties who need to know
                the business. They will process your personal data only in
                accordance with our instructions and are subject to
                confidentiality.
              </p>
              <br />
              <p>
                If you have reason to believe that your interaction with us is
                no longer secure (for example, if you feel that the security of
                any account you might have with us has been compromised), please
                immediately notify us of the problem by contacting via email or
                phone.
              </p>
            </Card>
          </div>

        
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">
                  Based On 2PH Travel
                </b>
              </h4>
              <br />
              <p>
                {`2PH Travel ("us", "we", or "our") operates the
              https://www.2phtravel.com website (hereinafter referred to as the
              "Service"). This page informs you of our policies regarding the
              collection, use and disclosure of personal data when you use our
              Service and the choices you have associated with that data. We use
              your data to provide and improve the Service. By using the
              Service, you agree to the collection and use of information in
              accordance with this policy. Unless otherwise defined in this
              Privacy Policy, the terms used in this Privacy Policy have the
              same meanings as in our Terms and Conditions, accessible from
              https://www.2phtravel.com`}
              </p>
              <br />
              <h4>
                <b className=" text-customBlue">Definitions</b>
              </h4>
              <p className="mt-3">
                {` Service is the http://www.2phtravel.com website operated by 2PH Travel Group`}
              </p>
              <br />
              <h4>
                <b className=" text-customBlue">Personal Data</b>
              </h4>
              <p className="mt-3">
                {` Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).`}
              </p>
              <br />
              <h4>
                <b className=" text-customBlue">Usage Data</b>
              </h4>

              <p className="mt-3">
                {`Usage Data is data collected automatically either generated using the Service or from the Service infrastructure itself (for example, the duration of a page visit).
Cookies are small files stored on your device (computer or mobile device).
`}
              </p>
              <br />
              <h4>
                <b className=" text-customBlue">
                  Information Collection and Use
                </b>
              </h4>
              <p className="mt-3">
                {`We collect several different types of information for various purposes to provide and improve our Service to you.`}
              </p>
            </Card>
          </div> */}

          {/* 
          <div className="m-3 md:m-6">
            <Card className={`${Styles.cardShadow} p-5`}>
              <h4>
                <b className="text-customBlue text-[20px]">
                  Examples of Cookies we use:
                </b>
              </h4>
              {ExamplesofCookies.map((item, index) => (
                <div key={index}>
                  <li>{item.content}</li>
                </div>
              ))}
            </Card>
          </div> */}
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
